apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app-service
spec:
  ports:
  - port: 80
    name: web-app
  clusterIP: None
  selector:
    app: web-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-stateful
spec:
  serviceName: "web-app"
  podManagementPolicy: "Parallel"
  replicas: 2
  selector:
    matchLabels:
      app:  web-app-service
  template:
    metadata:
      labels:
        app:  web-app-service
    spec:
      containers:
      - name: web-app
        image: httpd:2.4
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: aws-vol
          mountPath: /usr/local/apache2/htdocs
  volumeClaimTemplates:
  - metadata:
      name: aws-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
      storageClassName: gp2-custome
