apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: web-app
spec:
    containers:
        - name: web-app
          image: httpd:2.4
          resources:
            limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local-vol
              mountPath: /usr/local/apache2/htdocs
    volumes: 
        - name: local-vol
          hostPath:
                path: /home/admin/workdir/volume_mount/vol1